### ISSUE TITLE
Unity最新BuglyPlugin / BuglyInit的执行在Pixel2 XL Android P上会崩溃

### ISSUE THREAD

**Issue by CodeMasterYi** [BuglyDevTeam/Bugly-Android#5]
![12075919-b7f3-4941-b8bd-e1567d5eb4be](https://user-images.githubusercontent.com/10430162/45072958-c6a30b80-b10f-11e8-8022-9d7179c12cc6.png)

**Comment by JalenChen** [comment]
日志中，Bugly打印的错误符合预期，并不是导致崩溃的原因，麻烦打开SDK日志开关重新复现下，保存完整logcat日志发给我们，可以加群联系我们：130979883， @zhhp1121 Rocky关注下。

**Comment by CodeMasterYi** [comment]
这个问题好久以前提交的，我现在已经忘记了=。=如果有时间的话，我会再次测试一下~
